package io.github.xjet.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSName
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.Origin
import com.google.devtools.ksp.validate

class XJetProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    private val spiServices = LinkedHashSet<Pair<KSClassDeclaration, KSAnnotation>>()
    private val routes = LinkedHashSet<Pair<KSClassDeclaration, KSAnnotation>>()

    override fun process(resolver: com.google.devtools.ksp.processing.Resolver): List<KSAnnotated> {
        resolver.getSymbolsWithAnnotation(SPI_ANNOTATION).forEach {
            val declaration = it as KSClassDeclaration
            val annotation = declaration.annotations.firstOrNull { a -> a.annotationType.resolve().declaration.qualifiedName?.asString() == SPI_ANNOTATION }
            if (annotation != null) spiServices.add(declaration to annotation)
        }

        resolver.getSymbolsWithAnnotation(ROUTE_ANNOTATION).forEach {
            if (it !is KSClassDeclaration) {
                logger.warn("@XRoute is only supported on classes for now: $it")
                return@forEach
            }
            val declaration = it as KSClassDeclaration
            val annotation = declaration.annotations.firstOrNull { a -> a.annotationType.resolve().declaration.qualifiedName?.asString() == ROUTE_ANNOTATION }
            if (annotation != null) routes.add(declaration to annotation)
        }
        return emptyList()
    }

    override fun finish() {
        val registrations = spiServices.mapNotNull { (decl, annotation) -> toRegistration(decl, annotation) }
        val routeEntries = routes.mapNotNull { (decl, annotation) -> toRoute(decl, annotation) }

        val spiBody = if (registrations.isEmpty()) {
            "    // no @SpiService found in this module"
        } else {
            registrations.joinToString("\n") { reg ->
                "    registry.registerClass(\n" +
                    "        Class.forName(\"${reg.api}\") as Class<Any>,\n" +
                    "        Class.forName(\"${reg.impl}\") as Class<out Any>,\n" +
                    "        override = ${reg.override}\n" +
                    "    )"
            }
        }

        val routeBody = if (routeEntries.isEmpty()) {
            "    return emptyList()"
        } else {
            routeEntries.joinToString(",\n") { r ->
                "    RouteDescriptor(\n" +
                    "        path = \"${r.path}\",\n" +
                    "        group = \"${r.group}\",\n" +
                    "        title = \"${r.title}\",\n" +
                    "        targetClassName = \"${r.target}\"\n" +
                    "    )"
            }.let { "    return listOf(\n$it\n    )" }
        }

        val content = buildString {
            appendLine("// Generated by XJet KSP processor. Do not edit.")
            appendLine("package io.github.xjet.generated")
            appendLine()
            appendLine("import io.github.xjet.core.RouteDescriptor")
            appendLine("import io.github.xjet.spi.SpiRegistry")
            appendLine()
            appendLine("object XJetGeneratedSpi {")
            appendLine("    fun registerAll(registry: SpiRegistry) {")
            appendLine(spiBody)
            appendLine("    }")
            appendLine()
            appendLine("    fun routes(): List<RouteDescriptor> {")
            appendLine(routeBody)
            appendLine("    }")
            appendLine("}")
        }

        val file = codeGenerator.createNewFile(
            Dependencies(aggregating = true),
            "io.github.xjet.generated",
            "XJetGeneratedSpi",
            "kt",
        )
        file.use { it.write(content.toByteArray(Charsets.UTF_8)) }
    }

    private fun toRegistration(decl: KSClassDeclaration, annotation: KSAnnotation): Registration? {
        val apiValue = argument(annotation, "api") ?: run {
            logger.error("@SpiService on ${decl.qualifiedName?.asString()} is missing 'api'", decl)
            return null
        }
        val apiName = findClassName(apiValue) ?: run {
            logger.error("@SpiService.api must be a KClass type", decl)
            return null
        }
        val implName = decl.qualifiedName?.asString() ?: return null
        val override = argument(annotation, "override") as? Boolean ?: false
        val name = argument(annotation, "name") as? String ?: ""
        return Registration(api = apiName, impl = implName, override = override, name = name)
    }

    private fun toRoute(decl: KSClassDeclaration, annotation: KSAnnotation): RouteEntry? {
        val path = argument(annotation, "path") as? String ?: return null
        val group = argument(annotation, "group") as? String ?: "app"
        val title = argument(annotation, "title") as? String ?: ""
        val target = decl.qualifiedName?.asString() ?: return null
        return RouteEntry(path = path, group = group, title = title, target = target)
    }

    private fun argument(annotation: KSAnnotation, name: String): Any? {
        return annotation.arguments.firstOrNull { it.name?.asString() == name }?.value
    }

    private fun findClassName(value: Any?): String? {
        return when (value) {
            is KSClassDeclaration -> value.qualifiedName?.asString()
            is KSType -> (value.declaration as? KSClassDeclaration)?.qualifiedName?.asString()
            else -> null
        }
    }

    private data class Registration(
        val api: String,
        val impl: String,
        val override: Boolean,
        val name: String,
    )

    private data class RouteEntry(
        val path: String,
        val group: String,
        val title: String,
        val target: String,
    )

    companion object {
        private const val SPI_ANNOTATION = "io.github.xjet.annotation.SpiService"
        private const val ROUTE_ANNOTATION = "io.github.xjet.annotation.XRoute"
    }
}



